// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Component = require("./component.bs.js");

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Component.make, {}));
}

var make = App;

exports.make = make;
/* react Not a pure module */
