// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Tictactoe = require("./Tictactoe.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

require('./styles.css')
;

var reducer = Tictactoe.update;

function Component(Props) {
  var match = React.useReducer(reducer, Tictactoe.state);
  var dispatch = match[1];
  var state = match[0];
  var board = state.board;
  var positions = [
    "upper",
    "middle",
    "lower"
  ];
  var elements = Belt_Array.mapWithIndex(positions, (function (i, x) {
          var r = board[i];
          var v = function (x) {
            if (x === 1) {
              return "o";
            } else if (x === 2) {
              return "x";
            } else {
              return "";
            }
          };
          var v1 = v(r[0]);
          var v2 = v(r[1]);
          var v3 = v(r[2]);
          return React.createElement("div", {
                      className: "row"
                    }, React.createElement("div", {
                          className: "left_" + x + "",
                          onClick: (function (param) {
                              Curry._1(dispatch, /* Coords */{
                                    _0: i,
                                    _1: 0
                                  });
                            })
                        }, React.createElement("div", {
                              className: Tictactoe.cellStyle(i, 0, state, r[0])
                            }, v1)), React.createElement("div", {
                          className: "center_" + x + "",
                          onClick: (function (param) {
                              Curry._1(dispatch, /* Coords */{
                                    _0: i,
                                    _1: 1
                                  });
                            })
                        }, React.createElement("div", {
                              className: Tictactoe.cellStyle(i, 1, state, r[1])
                            }, v2)), React.createElement("div", {
                          className: "right_" + x + "",
                          onClick: (function (param) {
                              Curry._1(dispatch, /* Coords */{
                                    _0: i,
                                    _1: 2
                                  });
                            })
                        }, React.createElement("div", {
                              className: Tictactoe.cellStyle(i, 2, state, r[2])
                            }, v3)));
        }));
  return React.createElement("div", {
              id: "content"
            }, React.createElement("div", {
                  className: "wrapper"
                }, React.createElement("div", {
                      className: "field"
                    }), elements), React.createElement("button", {
                  className: "button",
                  onClick: (function (param) {
                      Curry._1(dispatch, /* Restart */0);
                    })
                }, "Restart"));
}

var make = Component;

exports.reducer = reducer;
exports.make = make;
/*  Not a pure module */
